[package]
name = "smartthermometer_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smarthome = {path = "../smarthome"}
anyhow = "1.0.57"
thiserror = "1.0.31"
